services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8082
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "8082:8082"
    volumes:
      - ./data.json:/app/data.json
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:8082}
        REACT_APP_UPLOADS_BASE_URL: ${REACT_APP_UPLOADS_BASE_URL:-http://localhost:8082/uploads}
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
